name: Go

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      # disable lint for now: https://github.com/sj14/recaptcha/runs/524376020
      # - name: Lint
      #   run: |
      #     go get -u golang.org/x/lint/golint
      #     golint ./...

      - name: Test
        run: go test -race ./...
